favorite_tags:
- uuid
- classify
- filter
background_settings:
  enabled: false
  sidebar_enabled: false
  header_banner_enabled: false
  sidebar_banner_enabled: true
  image_path: ''
  sidebar_image_path: ''
  header_banner_path: ''
  sidebar_banner_path: E:\1PIC\2503\2025音律联觉\2025音律联觉（2）.avif
  opacity: 0.5
  blur: 0
user_preferences:
  ui_settings:
    card_view:
      sidebar_settings:
        expander_order:
        - filter_tasks
        - edit_task
        - tag_filters
        - system
        use_sidebar_editor: true
        filter_tasks_enabled: true
        edit_task_enabled: true
        tag_filters_enabled: true
        system_enabled: true
