active_taskfile: D:\1VSCODE\Projects\LazyCommand\TaskGui\Taskfile.yml
background_settings:
  blur: 0
  enabled: false
  header_banner_enabled: false
  header_banner_path: E:\1PIC\22 · LOONG · 33_116538352_Criin.webp
  image_path: E:\1PIC\2503\Music!!!!!_128400400_Criin.avif
  opacity: 0.7
  sidebar_banner_enabled: true
  sidebar_banner_path: E:\1PIC\2503\2025音律联觉\2025音律联觉（2）.avif
  sidebar_enabled: true
  sidebar_image_path: ''
basic_settings:
  auto_backup: true
  auto_load_recent: true
  backup_interval: 30
  dark_mode: false
  max_log_files: 10
  notify_on_completion: true
  run_mode: sequential
  show_card_tab: true
  show_dashboard_tab: false
  show_preview_tab: false
  show_settings_tab: true
  show_state_tab: true
  show_table_tab: false
  show_welcome: true
card_group_by_tag: true
favorite_tags:
- classify
- filter
- organize
- upscale
- uuid
- workflow
merge_mode: false
pinned_tags:
- workflow
- filter
- pics
- organize
- upscale
- classify
- uuid
taskfiles:
- D:\1VSCODE\Projects\LazyCommand\TaskGui\Taskfile.yml
- D:\1VSCODE\GlowToolBox\Taskfile.yml
user_preferences:
  ui_settings:
    card_view:
      show_command: false
      show_description: false
      show_directory: false
      show_tags: true
      use_sidebar_editor: true
